name: Futbol Gündem APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Android SDK kur
        uses: android-actions/setup-android@v3

      - name: Android SDK paketlerini kur
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Gradle kur
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Wrapper oluştur
        run: |
          gradle wrapper --gradle-version 8.9

      - name: APK oluştur
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: APK'yı yükle
        uses: actions/upload-artifact@v4
        with:
          name: Futbol-Gundem-APK
          path: app/build/outputs/apk/debug/app-debug.apk
